WITH EMPLOYEES AS (
  SELECT 
    ID,
    NAME
  FROM TEMP_TABLE
  WHERE AGE > 30
), SALARIES AS (
  SELECT 
    ID, 
    DENSE_RANK() OVER (ORDER BY SALARIES.SALARY DESC) AS SALARY_RANK
  FROM SALARIES
  GROUP BY ID
) 
SELECT
  e.ID, 
  e.NAME, 
  s.SALARY_RANK
FROM EMPLOYEES e
JOIN SALARIES s
  ON e.ID = s.ID
;
